config:
  credentials: []
  project_repos: {}
environment: {}
sqa_criteria:
  QC.FAIR:
    repos:
      this_repo:
        commands:
        - '/bin/curl -H ''Content-Type: application/json'' -X POST -d ''{"id": "10261/157765",
          "repo": "oai-pmh", "oai_base": "http://digital.csic.es/dspace-oai/request"}''
          http://localhost:9090/v1.0/rda/rda_all'
        container: qc.fair_randy-smalt-beetle
timeout: 600
